"""Inicializa las tablas de la base de datos

Revision ID: 324c5eb3c909
Revises: 
Create Date: 2025-05-13 12:46:41.255595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer

# revision identifiers, used by Alembic.
revision = '324c5eb3c909'
down_revision = None
branch_labels = None
depends_on = None

# Tabla de usuario
usuario_table = table(
    'usuario',
    column('id', Integer),
    column('nombre', String),
    column('email', String),
    column('telefono', String),
    column('rol', String)
)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('nacionalidad', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('libro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('anio_publicacion', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['autor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_prestamo', sa.Date(), nullable=True),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.Column('devuelto', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['libro_id'], ['libro.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Insertar usuarios iniciales
    op.bulk_insert(usuario_table, [
        {'id': 1, 'nombre': 'Admin', 'email': 'admin@biblioteca.com', 'telefono': '123456789', 'rol': 'bibliotecario'},
        {'id': 2, 'nombre': 'Lector', 'email': 'lector@biblioteca.com', 'telefono': '987654321', 'rol': 'lector'}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestamo')
    op.drop_table('libro')
    op.drop_table('usuario')
    op.drop_table('autor')
    # ### end Alembic commands ###
